// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  images: dynamic(() => import("./Images")),
  rich_text: dynamic(() => import("./RichText")),
  text_block: dynamic(() => import("./TextBlock")),
};
